---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-project
spec:
  sourceRepos:
    - {{ .Values.repository.url }}
    - https://github.com/edgelevel/helm-charts.git
    {{- range .Values.argocd.sourceRepos }}
    - {{ . }}
    {{- end }}
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
