---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cerebro
spec:
  project: observe
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/cerebro
    helm:
      parameters:
        - name: config.hosts[0].host
          value: http://elasticsearch-master.observe:9200
        - name: config.hosts[0].name
          value: elasticsearch-observe
  destination:
    server: https://kubernetes.default.svc
    namespace: observe
