---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
spec:
  project: observe
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/fluent-bit
    helm:
      parameters:
        - name: rbac.create
          value: "false"
        - name: serviceAccount.create
          value: "false"
        - name: backend.type
          value: es
        - name: backend.es.host
          value: http://elasticsearch-master.observe
        - name: backend.es.port
          value: "9200"
  destination:
    server: https://kubernetes.default.svc
    namespace: observe
