---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-ops-view
spec:
  project: observe
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/kube-ops-view
    helm:
      parameters:
        - name: rbac.create
          value: "true" 
  destination:
    server: https://kubernetes.default.svc
    namespace: observe
