---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
spec:
  project: observe-project
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/prometheus-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: observe
