---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: argocd-project
  source:
    #repoURL: https://github.com/argoproj/argo-helm.git
    #path: charts/argo-cd
    repoURL: {{ .Values.repository }}
    path: bootstrap-unofficial/charts/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
