---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mobile-carrier-bot
spec:
  project: bot-project
  source:
    repoURL: https://github.com/niqdev/mobile-carrier-bot.git
    path: charts/app
    #targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: bot
