{{- if .Values.ambassador.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ambassador
spec:
  project: ambassador-project
  source:
    repoURL: https://github.com/helm/charts.git
    path: stable/ambassador
    helm:
      parameters:
        - name: replicaCount
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: ambassador
{{- end }}
