{{- if .Values.ambassador.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ambassador
spec:
  sourceRepos:
    - https://github.com/helm/charts.git
    - https://github.com/edgelevel/gitops-k8s.git
  destinations:
    - namespace: ambassador
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
{{- end }}
