---
apiVersion: v1
kind: Service
metadata:
  name: ambassador-service
  namespace: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  guestbook_mapping
      prefix: /guestbook
      service: guestbook-ui.guestbook
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: ambassador/v1
kind: Mapping
metadata:
  name: httpbin_mapping
  namespace: ambassador
spec:
  prefix: /httpbin/
  service: httpbin.org:80
  host_rewrite: httpbin.org
