---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  project: guestbook
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: guestbook
    #targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
