---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  guestbook_mapping
      prefix: /guestbook/
      service: guestbook-ui:80
spec:
  ports:
    - name: guestbook-ui
      port: 80
