---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  TCPMapping
      name:  guestbook_mapping
      prefix: /guestbook/
      port: 8081
      service: guestbook-ui:80
