# FIXME https://github.com/edgelevel/gitops-k8s/issues/6
dependencies:
  - name: argo-cd
    alias: argocd
    version: 0.2.2
    repository: https://argoproj.github.io/argo-helm
    condition: argocd.enabled
